# Generated by Django 5.2 on 2025-04-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('carbon_saved', models.CharField(max_length=100)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
