# Generated by Django 5.2 on 2025-05-08 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('carbon_saved', models.CharField(max_length=100)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='userchallenge',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='carbon_saved',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='xp',
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
    ]
